plugins {
    id 'java-library'
    id 'idea'
    id 'maven-publish'
    id 'net.neoforged.moddev' version '2.0.141'
}


version = "${mod_version} - ${minecraft_version}"
group = 'net.sshmoob.create_ca' // http://maven.apache.org/guides/mini/guide-naming-conventions.html

java.toolchain.languageVersion = JavaLanguageVersion.of(21)
//println "Java: ${System.getProperty 'java.version'}, JVM: ${System.getProperty 'java.vm.version'} (${System.getProperty 'java.vendor'}), Arch: ${System.getProperty 'os.arch'}"

sourceSets.main.resources {
    srcDir('src/generated/resources') //datagen :)

    // Exclude from final output
    exclude("**/*.bbmodel")
    exclude("src/generated/**/.cache")
}

neoForge {
    version = project.neo_version

    parchment {
        minecraftVersion = minecraft_version
        mappingsVersion = project.parchment_version
    }


    runs {
         client {
            client()
        }

        server {
            server()
        }

        data {
            data()
            // Specify the modid for data generation, where to output the resulting resource, and where to look for existing resources.
            programArguments.addAll(
                    '--mod',  project.mod_id,
                    '--all',
                    '--output',
                    file('src/generated/resources/').getAbsolutePath(),
                    '--existing',
                    file('src/main/resources/').getAbsolutePath()
            )
        }
        configureEach {
            //Logging configuration
            systemProperty 'forge.logging.markers', 'REGISTRIES'
            logLevel = org.slf4j.event.Level.DEBUG
        }
    }
    mods {
        "${mod_id}" {
            sourceSet(sourceSets.main)
        }
    }
}

configurations {
    runtimeClasspath.extendsFrom localRuntime
}

repositories {
    maven { url = "https://maven.createmod.net" } // Create, Ponder, Flywheel
    maven { url = "https://maven.ithundxr.dev/snapshots" } // Registrate
//    maven { url = "https://raw.githubusercontent.com/Fuzss/modresources/main/maven/" } // ForgeConfigAPIPort
    maven { url = "https://api.modrinth.com/maven" }
    maven {
        name = "CaffeineMC"
        url = "https://maven.caffeinemc.net/releases"
    }
    maven {
        name = "Sinytra"
        url = uri("https://maven.su5ed.dev/releases")
    }
}

dependencies {
//main dependencies
    implementation("com.simibubi.create:create-${minecraft_version}:${create_version}:slim") { transitive = false }
    implementation("net.createmod.ponder:ponder-neoforge:${ponder_version}+mc${minecraft_version}")
    compileOnly("dev.engine-room.flywheel:flywheel-neoforge-api-${minecraft_version}:${flywheel_version}")
    runtimeOnly("dev.engine-room.flywheel:flywheel-neoforge-${minecraft_version}:${flywheel_version}")
    implementation("com.tterrag.registrate:Registrate:${registrate_version}")

    if(enable_extras.toBoolean()) {
    //Not required, mostly QOL for dev
      //  implementation("maven.modrinth:modernfix:${modernfix_version}+mc${minecraft_version}")
        // I know, translation to EMI instead of just using JEI, but it mimics Create+ so...
        implementation("maven.modrinth:tmrv:${tmrv_version}+mc.21.1")
        implementation("maven.modrinth:emi:${emi_version}+${minecraft_version}+neoforge")

        // Modern Sodium in dev env shenanigans
        implementation("net.caffeinemc:sodium-neoforge-mod:${sodium_version}+mc${minecraft_version}")
        additionalRuntimeClasspath("net.caffeinemc:sodium-neoforge:${sodium_version}+mc${minecraft_version}") {
            transitive = false
        }
        implementation ("org.sinytra.forgified-fabric-api:fabric-api-base:${ffapi_base_version}")
        implementation ("org.sinytra.forgified-fabric-api:fabric-block-view-api-v2:${ffapi_block_view_version}")
        implementation ("org.sinytra.forgified-fabric-api:fabric-renderer-api-v1:${ffapi_renderer_version}")
        implementation ("org.sinytra.forgified-fabric-api:fabric-rendering-data-attachment-v1:${ffapi_render_data_attach_version}")

    }
}

// Example for how to get properties into the manifest for reading at runtime.
var generateModMetadata = tasks.register("generateModMetadata", ProcessResources) {
    var replaceProperties = [
            minecraft_version      : minecraft_version,
            minecraft_version_range: "[${minecraft_version}]",
            neo_version            : neo_version,
            loader_version_range   : "[1,)", //should match neoforge.mods.toml
            mod_id                 : mod_id,
            mod_name               : mod_name,
            mod_license            : mod_license,
            mod_version            : mod_version,
    ]
    inputs.properties replaceProperties
    expand replaceProperties
    from "src/main/templates"
    into "build/generated/sources/modMetadata"
}

/// Include the output of "generateModMetadata" as an input directory for the build
// this works with both building through Gradle and the IDE.
sourceSets.main.resources.srcDir generateModMetadata
// To avoid having to run "generateModMetadata" manually, make it run on every project reload
neoForge.ideSyncTask generateModMetadata

publishing {
    publications {
        register('mavenJava', MavenPublication) {
            from components.java
        }
    }
    repositories {
        maven {
            url "file://${project.projectDir}/repo"
        }
    }
}


tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8' // Use the UTF-8 charset for Java compilatione
}

//Audtomatic Source and Javadoc downloading since IntelliJ stopped doing it automatically.
idea {
    module {
        downloadSources = true
        downloadJavadoc = true
    }
}
