# Sets default memory used for gradle commands. Can be overridden by user or command line properties.
# This is required to provide enough memory for the Minecraft decompilation process.
org.gradle.jvmargs=-Xmx4G
org.gradle.daemon=false

mod_version = 2.0c
minecraft_version=1.19.2
forge_version=43.3.13
mixin_version=0.8.5

#mod dependency versions
registrate_version = MC1.19-1.1.5
create_version = 0.5.1.f
create_build_number = 45
flywheel_version = 0.6.10-20
#QOL for when I'm testing
jei_version = 11.6.0.1019-forge
emi_version = 1.1.2+1.19.2+forge
modernfix_version = 5.13.0+mc1.19.2-forge
embeddium_version = 0.3.3+mc1.19.2-forge
# (Create+ modpack) mods that have integration
#Create compat recipe
berry_good_version = 6.1.0
blueprint_version = 6.2.0